### ISSUE TITLE
Can't build swift2 branch with Carthage in xcode 7 beta 6

### ISSUE THREAD

**Issue by Visorox** [pluralsight/PSOperations#1]
```
The following build commands failed:
	CompileSwift normal x86_64 /Users/jamie/Documents/code/sia-iOS/Carthage/Checkouts/PSOperations/PSOperationsTests/PSOperationsTests.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)

/Users/jamie/Documents/code/sia-iOS/Carthage/Checkouts/PSOperations/PSOperationsTests/PSOperationsTests.swift:9:18: error: module 'PSOperations' was not compiled for testing
A shell task failed with exit code 65:
** BUILD FAILED **```

**Comment by mcmurrym** [comment]
I don't know much about Carthage so I'll need some more details. If we have to add carthage support to the repo I'll invite you to go for it :)

**Comment by Visorox** [comment]
I've had a quick look into this. Carthage is building with the Release configuration for which ENABLE_TESTABILITY is false (for obvious reasons).

In the scheme for build it builds both the PSOperations target and the PSOperationsTests target. Do you know of a way to turn this off for release builds?

**Comment by Visorox** [comment]
Here's more details about this issue https://github.com/Carthage/Carthage/issues/517

**Comment by Visorox** [comment]
Brilliant. It works for me now!
