### ISSUE TITLE
New cocoapods version with bugfixes and improvements

### ISSUE THREAD

**Issue by etulusha-auto1** [pluralsight/PSOperations#103]
The last release of cocoa pods version was v3.0.0 on Oct 2016. What about to release v3.1.0 with current muster branch?

**Comment by MarkQSchultz** [comment]
I'll get on this now. Thanks.

**Comment by MarkQSchultz** [comment]
Ok, updated and released v4.0.0. Seeing as to how this is a new version of swift and there were a number of fairly large fixes/changes, I decided to go with a major update.
