### ISSUE TITLE
Remove Calendar from Core

### ISSUE THREAD

**Issue by sean7512** [pluralsight/PSOperations#104]
When using core, we are forced to add ```NSCalendarsUsageDescription``` to our app's info.plist even though we do not use EventKit.  Can this be pulled out like Passbook and Health has been pulled out?

**Comment by mcmurrym** [comment]
I think that is a great idea. Feel free to submit a pull request with the solution, alternatively you'll have to wait till we get to it.

**Comment by sean7512** [comment]
Sounds good, if I get around to it before you, I'll put up a pull request.

**Comment by axello** [comment]
Discussion: I'm busy splitting the Calendar away, and wonder if LocationCapability should not *also* go into it's separate subspec? As you would need either one of the NSLocationAlwaysUsageDescription, NSLocationAlwaysAndWhenInUseUsageDescription or NSLocationWhenInUseUsageDescription keys when you use the CoreLocation manager.

Or is Apple not so picky as regards to the CoreLocation plist entry as to the Health, Calendar and Passbook entries?

**Comment by mcmurrym** [comment]
Unless Apple complains about those just leave them. IMO the real problem is Apple. They have decided if you have certain imports (i.e. HealthKit) and don't use the code, you still need to explain why. Boo.

**Comment by sean7512** [comment]
On our last app submission, they only flagged us for missing the calendar description.  Our app does not use location and we were not required to add in a NSLocationAlwaysUsageDescription.  Although, that can change at any time.

**Comment by axello** [comment]
Okay, I will leave that out for now. My app does use CoreLocation. Thanks for the swift response!
Busy on the changes now.

**Comment by axello** [comment]
Pull request created.
