### ISSUE TITLE
Remove Location from Core

### ISSUE THREAD

**Issue by gregoiredx** [pluralsight/PSOperations#109]
As suspected by @sean7512  in [Remove Calendar from Core](https://github.com/pluralsight/PSOperations/issues/104#issuecomment-372448720),  Apple is now complaining for missing NSLocationAlwaysUsageDescription and NSLocationWhenInUseUsageDescription even though we don't use CLLocationManager in our app.
Can this be pulled out like Calendar has been pulled out?
I may try to submit a pull request if you're OK with the idea.

**Comment by gregoiredx** [comment]
I've submitted a [pull request](https://github.com/pluralsight/PSOperations/pull/110).

**Comment by mcmurrym** [comment]
done.
