### ISSUE TITLE
Should the observer.operationDidFinish be called after state = .finished

### ISSUE THREAD

**Issue by bmkor** [pluralsight/PSOperations#113]
https://github.com/pluralsight/PSOperations/blob/69b5905a66b07aa4829621c70f4aff7f29ccf455/PSOperations/Operation.swift#L350-L354

Just wondering if the `state = .finished` should be before the `for observer in observers ...`. 
The reasons are

* the description says operationDidFinish;
* the execution code in the `operationDidFinish` may assume the operation is finished; for example, its operationqueue will not contain the operation if it is marked as finished.

**Comment by jjatie** [comment]
Are you proposing an `operationWillFinish` method? Changes to this behaviour would break many observers in my code, and I imagine many others'.
