### ISSUE TITLE
Swift 5 errors - bridging errors in Dynamic Framework

### ISSUE THREAD

**Issue by agiguere** [pluralsight/PSOperations#121]
I have a dynamic framework, inside my framework I have 2 others target, a test target and a demo target (demo app to test my framework)

my framework compiled successfully but I could not used it in other targets because of the errors below

I could see my operation subclasses but Xcode don't know if they are related to PSOperations or NSOperations

Example:

SWIFT_CLASS("_TtC9Dollarama14ParseOperation")
@interface ParseOperation : Operation
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end
Cannot find interface declaration for 'Operation', superclass of 'ParseOperation'; did you mean 'NSOperation'?

thanks

**Comment by agiguere** [comment]
sorry for the code and paste, here is a clean one

```
SWIFT_CLASS("_TtC9Dollarama14ParseOperation")
@interface ParseOperation : Operation
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end
```

**Comment by agiguere** [comment]
my code was working fine before Xcode 10.2 / Swift 5

here is how I declare my class in my framework


```
import PSOperations

open class ParseOperation: PSOperations.Operation {
  ...
}
```

**Comment by mcmurrym** [comment]
depending on how you are integrating the library you may run into problems. master currently is on swift 4, I have a swift 5 branch I will be merging very soon

**Comment by agiguere** [comment]
we are using Carthage, I tried both branch master & swift 5 and same results, thanks

**Comment by mcmurrym** [comment]
I don't personally use carthage so I won't be able to provide much help here. If I run into this when migrating via the way we use it, I'll certainly be able to look into it more.

**Comment by agiguere** [comment]
I was able to recreate the problem in a small project, only 1 file and push it to my github account,

if you have time please have a look, not sure it's related to carthage, the PSOperations is compiled by Carthage and could be include in my Single App without any problem, but in my app if I tried to include the main framework, it failed, if you check the xcode bridging file (xxxx-Swift.h), it looks like it is confuse because you used the same name for you operation as Apple (Operation)

https://github.com/agiguere/MySwift5Framework

thanks

**Comment by mcmurrym** [comment]
I'll try to look at this sometime soon. The truth is, Apple chose to use the same name we have. Apple renamed from `NSOperation` to `Operation` so when Swift 3 rolled out we created the `PSOperation` typealias, depending on the project configuration, I could see it being a problem still.

**Comment by agiguere** [comment]
please wait, it looks like a carthage errors, I posted the errors there and they are investigating it and will release a new version soon ... I will keep this issue open just in case it's not carthage and we will close it as soon as I got new from them, thanks

**Comment by agiguere** [comment]
Hi Matt, I am still waiting for a Carthage release but in the meantime I did this test and it works.

I created an iOS  dynamic framework with a single application as a new target and
instead of adding your dependency (with carthage), I added AFNetworking
and it turn out it works, no compile errors.

when you have time please have a look at the error in my test repo
https://github.com/agiguere/MySwift5Framework

one of our options right now to move on with Swift 5 is to
fork your repo and rename all operations to something else to avoid conflict name
right now it's difficult for me to say if this bug is related to your API or the way Carthage bundle your repo as a framework

thanks

**Comment by agiguere** [comment]
this issue has been fixed by the carthage team, (carthage version 0.33 for Swift 5)
