### ISSUE TITLE
Published as a Cocoapod?

### ISSUE THREAD

**Issue by gblotter** [pluralsight/PSOperations#16]
Hey, just checking in to see if you guys have published this as a cocoapod yet

**Comment by MarkQSchultz** [comment]
We have pushed a tag (`2.0`) to master. We are now waiting on @sstigler to make some changes on PR #14. Once he (or anyone else) makes those changes, I can work on publishing the pod to `trunk`, or whatever it is that's necessary.

**Comment by MarkQSchultz** [comment]
@gblotter If you want this to get done sooner, you could replicate the changes in your own PR and I'll merge it.

**Comment by gblotter** [comment]
So if I understand correctly, it's the conformance to the 2.0 tag you're waiting for on PR #14 ?

**Comment by MarkQSchultz** [comment]
That and the line notes added, namely:

Could you add
`s.watchos.deployment_target = '2.0'`
and
`s.osx.deployment_target = "10.11"`?

**Comment by MarkQSchultz** [comment]
Along with the changes he made in https://github.com/sstigler/PSOperations/commit/dd659f19bdd8a7598775abb7ca1ee6496b618c44

**Comment by gblotter** [comment]
Ok, if I have time today I'll try and get that done. Thanks for your patience with me ;)

Thanks,

Geoff

--
Geoffrey Blotter
(801) 7(tel:(801)%20717-7837)17-7837(tel:(801)%20717-7837)

**Comment by MarkQSchultz** [comment]
Also, I hear you're working with my good friend @corykon now!

**Comment by gblotter** [comment]
Yessir.. maybe I'll have him fix this, as he learns how to Swift!

**Comment by gblotter** [comment]
So...  #14 TVOS support... I actually disagree putting this in to your main branch, as the software/SDK is still in beta.  Just to lint the podfile, I'd have to install a beta version of Xcode to pull down a tvos simulator.  It's not hard to add in the future, but for me, I would put this in a beta branch.  Those are just my two cents.

The rest of those changes are ready and I can create a PR anytime

**Comment by MarkQSchultz** [comment]
I think I agree with you. If putting in the tvOS support requires you to run a beta Xcode, then it shouldn't be in master.

**Comment by gblotter** [comment]
Ok, I just created a PR... #17 with the stuff that you were looking for.  Let me know if you need any changes.  I left out TVOS, it could possibly go in a separate branch.

**Comment by MarkQSchultz** [comment]
Cool. I'll merge it when the build finishes, though you didn't make any changes that should affect the build status. After merging, I'll try and finish up whatever else is needed to officially publish the pod.

**Comment by MarkQSchultz** [comment]
https://twitter.com/CocoaPodsFeed/status/653612490178301952

**Comment by gblotter** [comment]
Rock on, thanks!
