### ISSUE TITLE
Working with NSOperation subclasses

### ISSUE THREAD

**Issue by maremmle** [pluralsight/PSOperations#22]
Hi, 

I am working with both `NSOperation` subclasses (in particular CloudKit's `CKOperation`) and `PSOperation` classes at the same time. In order to be able to take advantage of the additional features, such as the conditions or `finishWithError()`, I would need to subclass all my Operations from the `Operation` base class. Obviously I can not do that for `CKOperation` subclasses. So I am wrapping any `CKOperation` in `GroupOperation` in those cased where I want to use the additional features by `PSOperation`. 

I was wondering if there is any better way.

**Comment by MarkQSchultz** [comment]
@maremmle, I think you're probably doing it the best way. The only alternative I can think of is to create a `GroupOperation` subclass that takes an `NSOperation` and a condition. It would essentially do what you're already doing, except maybe do it all in the `init` instead. For example:

```
class ConditionedOperation: GroupOperation {
    init(operation: NSOperation, condition: OperationCondition) {
        super.init(operations: [operation])
        addCondition(condition)
    }
}
```

Disclaimer: I haven't tried compiling that at all.

This would allow for less code duplication. Could be more convenient I guess to package it up like that.
¯\\\_(ツ)\_/¯

**Comment by MarkQSchultz** [comment]
Closing this issue. Feel free to continue the discussion though. I'd be glad to help out however I can. Either way, probably not a change that needs to be made to the `PSOperations` library itself, but could be made in your own project.
