### ISSUE TITLE
Dependent operation doesn't start

### ISSUE THREAD

**Issue by kevinbrewster** [pluralsight/PSOperations#32]
When I run the below code in simulator, "OP2 DONE" only prints out ~5% of the time. 

``` swift
class ViewController: UIViewController {
    let queue = OperationQueue()

    override func viewDidLoad() {
        super.viewDidLoad()

        queue.maxConcurrentOperationCount = 1

        let op1 = BlockOperation {
            NSLog("OP1 DONE")
        }
        queue.addOperation(op1)

        let op2 = BlockOperation {
            NSLog("OP2 DONE")
        }
        op2.addDependency(op1)
        queue.addOperation(op2)

        let op3 = BlockOperation {
            NSLog("OP3 DONE")
        }
        queue.addOperation(op3)
    }
}
```

Seems to be a bug in Operation.swift in "override public var ready". Problem area is here:

``` swift
// Until conditions have been evaluated, "isReady" returns false
_ready = false
```

My code works as correctly if I change to:

``` swift
// Until conditions have been evaluated, "isReady" returns false
_ready = state == .Ready && (super.ready || cancelled)
```

I'm not sure if this is the correct solution though.

**Comment by mcmurrym** [comment]
@kevinbrewster Test your problem on the latest master (not synced with cocoa pods yet) It may or may not fix it. We are aware of an issue when `maxConcurrentOperationCount` is set to 1 that still exist and may be what you are seeing. You are welcome to try your code change and run the tests against them and submit a pull request.

**Comment by niklassaers** [comment]
@mcmurrym Could you tell a bit more about the maxConcurrentOperationCount == 1 situation? I may have run into it, where operations with dependencies and the dependencies themselves get stuck while being .Ready and operations without dependencies running through the NSOperationQueue without a problem. Increasing maxConcurrentOperationCount to 4 solved the problem, but I wanted to have it as 1 to be able to debug that things actually are performed in the order I expected them to.

**Comment by craigmarvelley** [comment]
@niklassaers possibly related to this? https://github.com/pluralsight/PSOperations/commit/255717a3d755ec1efb2203b9e19ffa8cefc7097e#diff-2aafa95fccf992bfd34d33bb7e6eeb4aR667

FWIW I've been seeing a similar issue to yours on [this repo](https://github.com/inspace-io/INSOperationsKit) which is a port of PSOperations to Objective-C. Your fix from above, applied to that repo, also fixes the issue I was seeing there, where if I queued up a bunch of chained operations more often than not the queue would randomly stop processing them before it reached the end.

**Comment by mcmurrym** [comment]
This may be fixed, please try the latest.

**Comment by mcmurrym** [comment]
I'm going to close this as I never heard anything back on whether or not it is a problem with the latest changes.
