### ISSUE TITLE
Completion Block called twice

### ISSUE THREAD

**Issue by jeremyquinn** [pluralsight/PSOperations#35]
I have classes extending Operation, that add a completionBlock to self during init, to run a custom completionBlock.
The completionBlock is running twice.
There was a similar problem with Dan Thorpe's Operations GitHub project, it looks very similar : https://github.com/danthorpe/Operations/issues/123

**Comment by mcmurrym** [comment]
I think the fix should be not allowing `completionBlock` property to operate at all within `PSOperations`. We have seen this issue, we have also seen weird time of the execution of the block which makes the state of the operation in the `completionBlock` inconsistent (regardless of `PSOperations`). I believe @davedelong has even filed a radar to have this property deprecated. If you want to execute code at the end of an operation try the `Observer` class, you can easily do it with `BlockObserver` and it will _always_ execute at the expected time.

**Comment by davedelong** [comment]
I'd totally be in favor of seeing this property marked as unavailable. And yes, I did file that bug: <rdar://problem/23915499> Deprecate completionBlock

**Comment by jeremyquinn** [comment]
Hi Guys
Thanks for this. 
Yes, I worked around the problem by performing the custom completion block either in a defer clause in Operation.execute or in the case of a GroupOperation, wrapped in a BlockOperation, with the correct dependencies to run last.
This is such a great framework, thanks for all of your work!!

**Comment by mcmurrym** [comment]
We have now deprecated the completionBlock property within PSOperations.
