### ISSUE TITLE
calling finish() inside of execute causes completionBlock to execute twice

### ISSUE THREAD

**Issue by mcmurrym** [pluralsight/PSOperations#4]
When finish() is called within execute() (or main(), which execute() is in) The completionBlock property of NSOperation executes twice. I think this is because we switch to finished state while in main (the first completionBlock execution because of KVO messages being sent) and when main exits the operation is then asked if it is finished and it executes the completionBlock a second time.

**Comment by mcmurrym** [comment]
The simple solution is, don't use completionBlock as it is a little bit mysterious anyway.

**Comment by MarkQSchultz** [comment]
Not going to fix for now, but is a problem still.
