### ISSUE TITLE
Problem with App extensions

### ISSUE THREAD

**Issue by matteomatassoni** [pluralsight/PSOperations#51]
Both the `PushCapability` class and `UserNotification`struct uses UIApplication.sharedApplication() to invoke notification APIs, which as it is stated inside Apple documentation is not available in app extensions.

**Comment by MarkQSchultz** [comment]
We have already merged fixes for this into master. Are you using cocoapods or carthage?

**Comment by matteomatassoni** [comment]
I'm using cocoapods

**Comment by MarkQSchultz** [comment]
Ok, I'll add a new tag and push to trunk

**Comment by MarkQSchultz** [comment]
Ok, I pushed to trunk. Should be version 2.2.0. Try it out and let me know how it goes.

**Comment by MarkQSchultz** [comment]
@matteomatassoni I'm going to close this issue for now. Let me know if there's still a problem.
