### ISSUE TITLE
GroupOperation Produce vs Add Operation

### ISSUE THREAD

**Issue by agiguere** [pluralsight/PSOperations#55]
This is not an issue, since there is not much documentation about it I have to ask!

In a group operation, it seems there are 2 ways of creating a new operation

let say my group operation has 3 operations [A, B, C]

I want to produce operation C after operation B but only if B finish successfully

I do this in method operationDidFinish

I check for Operation B then create operation C

I could use addOperation(C) or produceOperation(C)

what is the best practice?

so far so good, I am using this framework in my app and I love it

thanks

**Comment by purrrminator** [comment]
Personally, I see only one difference between those two: `produceOperation` triggers the observer if you have set up one.

**Comment by agiguere** [comment]
yes I also see that addOperation will trigger this method

func operationDidFinish(operation: NSOperation, withErrors errors: [NSError])

but not produceOperation, so if you are waiting for an operation to finish to create a new one, the right choice seems to be addOperation

last question: logically operation dependancy should only execute if preceding operations succeeded, however this is not how apple design it, dependancy only garantee the order

In the example of a group operation encapsulating a download & parse request, you can only parse if you download request succeeded, I see 2 approach of solving this

either you add your dependencies right at the beginning and upon execution you check if you previous operation successed or not (the parse operation will check it's dependancy for the download operation and verify if there is something to parse)

OR you create you subsequent operation (parse) after evaluating the result of your first operation in method operationDidFinish, that means you will always initialize your group operation with one operation and create you subsequent operation after evaluating the result

From a coding perspective, it's easier to create all your dependencies before adding them to the queue, but logically it make more sense to add the parse operation only if the download request pass by creating the operation after the download operation finish 

what is the best practice?

thanks

**Comment by purrrminator** [comment]
I don't know the best practice, but I prefer the second way.

**Comment by agiguere** [comment]
thanks!
