### ISSUE TITLE
Operation _internalErrors should be public

### ISSUE THREAD

**Issue by agiguere** [pluralsight/PSOperations#58]
The array of internal errors should be public in class Operation

private var _internalErrors = [NSError]()

Example: in a group operation when producing a new operation, sometimes you don't need the first error of your first operation because you will generate a new one and at the end, you only need the last errors .... You should make this array pubic or provide an API to reset the array

let me know what you think

thanks

**Comment by mcmurrym** [comment]
See https://github.com/pluralsight/PSOperations/pull/56
