### ISSUE TITLE
Crash when two threads check readiness concurrently. 

### ISSUE THREAD

**Issue by bwhiteley** [pluralsight/PSOperations#6]
I've seen a crash twice when two threads are in the getter for Operation.ready at the same time. 
The prior state was .Pending. Both threads end up in evaluateConditions, and try to set the state to .EvaluatingConditions. The second thread hits the assertion at Operation.swift:129
                  assert(_state.canTransitionToState(newState, operationIsCancelled: cancelled), "Performing invalid state transition.")
At this point the prior state is .EvaluatingConditions and the new state is .EvaluatingConditions.

**Comment by mcmurrym** [comment]
This is going to be hard to consistently repo. I know one change we can make is to follow the multi-reader pattern so only writing the state will have an exclusive lock on `_state` and concurrent reads will not wait on one another.

**Comment by purrrminator** [comment]
same issue happens to me

**Comment by ThomasSempf-Stendahls** [comment]
same here

**Comment by mcmurrym** [comment]
okay... I'll try to give this attention soon.

**Comment by MarkQSchultz** [comment]
@purrrminator and @ThomasSempf-Stendahls are you sure you are not adding the same instance of the operation to 2 queues? Otherwise, how are 2 different threads acting on the state of the same operation?

**Comment by purrrminator** [comment]
@MarkQSchultz I'm pretty sure I'm not doing this. I have only one non-concurent singleton queue in my app. The problem seems to solved to me, but I can't remember how. I might have been finished the operation (calling `finish()`) *before* it actually done all the work.

**Comment by bwhiteley** [comment]
I'm sure I'm not adding it to 2 queues. It seems to be a race condition, so I don't have a consistent way to reproduce it. I do have a lot of crash reports all pointing to the same problem.

**Comment by MarkQSchultz** [comment]
NSOperationQueue throws if an operation is added to more than 1 queue. The logic in OperationQueue was asserting before NSOperationQueue has a chance to check and throw. I've created a solution for this. #23 If you could review it and let us know what you think, that would be great.

**Comment by MarkQSchultz** [comment]
Hey all, we believe we have a fix for this, please review #30. Thanks!

**Comment by MarkQSchultz** [comment]
#30 was merged. This is fixed.
