### ISSUE TITLE
Swift 2.3 compatibility

### ISSUE THREAD

**Issue by gblotter** [pluralsight/PSOperations#67]
Would love to see this framework updated for Swift 2.3 compatibility!!

**Comment by agiguere** [comment]
same for me, I have a couple of enterprise apps that depend on this framework and we are currently starting the process of testing iOS 10, can we have an ETC when this will be done

thanks

alex

**Comment by argie9999** [comment]
+1

**Comment by MarkQSchultz** [comment]
FYI @agiguere and @argie9999, there is a PR (#68 ) for this. It's not passing the automated build. So as soon as someone makes the necessary changes, we can merge it.

**Comment by gblotter** [comment]
Working on it...

**Comment by MarkQSchultz** [comment]
@gblotter @agiguere @argie9999 I'm curious why you guys are choosing swift 2.3 over swift 3 and when you'll make the switch to swift 3

**Comment by gblotter** [comment]
@MarkQSchultz it was my understanding that Swift 3 was still changing... I figured that Swift 2.3 would be more stable.

**Comment by MarkQSchultz** [comment]
That's accurate. There have been changes with every beta of Xcode. So when Xcode is released and no more swift changes are going in, are you going to migrate to Swift 3?

**Comment by gblotter** [comment]
That's the plan...

**Comment by MarkQSchultz** [comment]
Sounds good. Just trying to figure out what we do when xcode is released. I'd rather not have to support multiple versions of swift at that point.

**Comment by gblotter** [comment]
Hmm...  I'd suggest that when that time comes you either branch or tag and then have the disclaimer that you're not offering continuous support for Swift 2.3... but that branch will build, etc.

**Comment by gblotter** [comment]
@MarkQSchultz - Also, I don't know the time line of some of the other frameworks I use in my project and when they're going to be switching over to Swift 3.0, so this seems like a good step.

**Comment by agiguere** [comment]
I tried to update my project using Xcode 8 beta 4 with your branch swift2_3 and I got the following error

Module file was created by an older version of the compiler; rebuild 'PS Operations' and try again:

I also change the build settings for Use Legacy Swift Language Version to YES (for swift 2.3)

any idea?

**Comment by gblotter** [comment]
@agiguere What version of Xcode is your command line tools using?  I got that when I had compiled PSOperations (via Carthage) w/ Xcode 7.3 command line tools.  I changed it to Xcode 8 and recompiled, and it went away.

**Comment by agiguere** [comment]
@gblotter that make sense, but how do you specify that carthage should use Xcode 8 vs Xcode 7 ?

thanks

**Comment by gblotter** [comment]
@agiguere: 

`Xcode -> Preferences -> Locations -> Command Line Tools`

**Comment by agiguere** [comment]
@gblotter thanks

I download the latest version of carthage 0.17.2 and now I got the following error

maybe I should go back to my previous version 0.16.2 cause I was able to run & build the framework with no problem

warning: no umbrella header found for target 'PSOperationsHealth', module map will not be generated
warning: no umbrella header found for target 'PSOperationsHealth', module map will not be generated
A shell task (/usr/bin/xcrun xcodebuild -project /Users/alexandregiguere/Desktop/TestOperation/Carthage/Checkouts/PSOperations/PSOperations.xcodeproj -scheme PSOperationsHealth -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** CLEAN FAILED **

any idea?

thanks

**Comment by agiguere** [comment]
@gblotter I successfully build the framework for PSOperation and that's the only thing I needed,

however these errors were for the PSOperationHealth and Passbook, these frameworks have not been generated

Like I said it was working before and the only thing I changed was to update carthage to latest version and change the command line tools for Xcode 8, it's either one of them that cause this error

thanks

**Comment by agiguere** [comment]
a little bit disappointed that you opt for swift 2.3 over swift 3,

you should offer  branch to swift 3, since we can't mix swift 2.3 & swift 3.0, I will have to stick with swift 2.3 (which will die anyway) in all my projects,

I like to used the latest and greatest

**Comment by MarkQSchultz** [comment]
@agiguere I have a few thoughts:

1. This is simply an issue and a PR. Nothing has actually been done yet. Nothing has been merged. There is still potential for Swift 3.0 support.
2. Even if it was merged, this is open source. That means that you could just as easily submit a PR with Swift 3.0 support if that's what you think is correct
3. You were the very first person to reply and say that you, too, wanted Swift 2.3 support! See your comment at https://github.com/pluralsight/PSOperations/issues/67#issuecomment-235465326

Needless to say, I'm at least a little confused in regards to your last comment...

**Comment by mcmurrym** [comment]
When you wait long enough... a bug is no longer important :/ sorry for the inconvenience.
