### ISSUE TITLE
Swift 3 - Method does not override any method from its superclass

### ISSUE THREAD

**Issue by agiguere** [pluralsight/PSOperations#77]
After migration, I got this error:

Method does not override any method from its superclass

My class is a subclass of GroupOperation and I have a redefinition on operationDidFinish

it used to work, I check the new method definition, its mark as OPEN so I should be able to subclass it in Swift 3, don't know yet why the compiler is complaining

class StartupOperation: GroupOperation {
...
override func operationDidFinish(_ operation: PSOperations.Operation, withErrors errors: [NSError]) {
....

strange, any idea?

thanks

**Comment by MarkQSchultz** [comment]
Are you on the Swift3 branch?

**Comment by agiguere** [comment]
yes

**Comment by MarkQSchultz** [comment]
I see the issue. Compare the two signatures. 

From `GroupOperation`:
`open func operationDidFinish(_ operation: Foundation.Operation, withErrors errors: [NSError]) {`

and yours:
`override func operationDidFinish(_ operation: PSOperations.Operation, withErrors errors: [NSError]) {`

**Comment by agiguere** [comment]
right on!!

thanks
