### ISSUE TITLE
A possible deadlock when getting & setting Operation State?

### ISSUE THREAD

**Issue by bmkor** [pluralsight/PSOperations#85]
Would like to know if we could get the following deadlock when changing the state of an operation under multithreading. 

I hope that this hypothetical is possible and I may have missed some important concepts in the mechanism of recursive lock.

Discussions are appreciated. In fact, I would like to thank anyone who spent their precious time on reading my hypothetical example below. Thanks.

###########################################################################

Suppose we have an operation having state being "pending", and we have two threads namely, A & B, both trying to read the state of this operation and then modifying it later. 

Could we have the following? The lock and unlock indicate what the locking from the stateLock, an instance of NSRecursiveLock.

Thread A will get state (which is pending)
**Lock**
Thread A did get state (which is pending)
**Unlock**

Thread B will get state (which is pending)
**Lock**
Thread B did get state (which is pending)
**Unlock**

Thread A will set state (which is pending)
**Lock**
Thread A did set state (which is Ready after evaluating conditions)
**Unlock**

Thread B will set state (which is pending)
**Lock**
Thread B getting crash on the assert(state == .pending && !isCancelled) when evaluating conditions as state has been updated to Ready by Thread A.

**Comment by mcmurrym** [comment]
Were you actually seeing this issue?

**Comment by bmkor** [comment]
> Were you actually seeing this issue?

No. A few unexplainable crashed gave me this thought. Anyway, those crashes are not seen in the current version. Thanks a lot.
