### ISSUE TITLE
Operations using conditions can get stuck

### ISSUE THREAD

**Issue by jimabc** [pluralsight/PSOperations#93]
It appears PSOperations is susceptible to a race condition in which using conditions (MutuallyExclusive, in my case) can prevent dependent operations from executing, even though `super.isReady == true`.

**Sample Project**
I've put together a sample project to demonstrate the issue and though it's an attempt to brute force the issue, it does manifest in more typical use cases at scale.  The example reproduces 100% of the time on my iPhone 7+ running running iOS 10.3.2, however, it only occasionally repros on the simulator.  You can tell when it hits the race condition because the operation count will appear to get stuck, rather than decreasing.

[PSOperationsRaceCondition.zip](https://github.com/pluralsight/PSOperations/files/1153417/PSOperationsRaceCondition.zip)

**Related Discussions**
* https://github.com/Kabal/Operative/issues/51
* https://github.com/Kabal/Operative/pull/52
* https://github.com/ProcedureKit/ProcedureKit/issues/175
* https://github.com/robertmryan/Operation-Test-Swift/issues/2

**Comment by king7532** [comment]
@jimabc did this ever get fixed? Have you tested with the tip of master?

**Comment by jimabc** [comment]
@king7532 I ran the sample project again on iOS 11.2.1 and it's no longer reproducible.  Since posting the original issue my workaround was to stop using the MutuallyExclusive condition.

**Comment by mcmurrym** [comment]
We have made a lot of changes since this issue was submitted. I apologize for not responding sooner. I believe this is fixed for iOS 10 as well as iOS 11. If you could verify that it is not a problem on iOS 10 any more that would be great!

**Comment by jimabc** [comment]
Thanks for the update @mcmurrym. Since my last post I've stopped using PSOperations and will close this issue as it didn't seem to be common amongst the community.
