### ISSUE TITLE
Swift 4 -> 2 branches ?

### ISSUE THREAD

**Issue by agiguere** [pluralsight/PSOperations#95]
I am starting migrating my apps to Swift 4 / iOS 11, I can see there are 2 branches for Swift 4 ?

which one should I use ?

thanks

**Comment by pjcau** [comment]
Hi guys, 
have news on swift 4 support?

thank

**Comment by MarkQSchultz** [comment]
Master is already migrated to Swift 4 and the other branches are gone. 🙂
